name: edil_client
description: EDIL AI Tutor Flutter app (MVP demo)
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  animations: ^2.0.11
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/learning_paths.json
    - assets/
