runtime: python312
instance_class: F2
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  ENV: production
  AUTH_STUB: false
  LLM_PROVIDER: gemini
  LLM_MODEL: gemini-2.5-flash-lite
  FIREBASE_PROJECT_ID: edilmai
  VERTEX_PROJECT_ID: edilmai
  VERTEX_LOCATION: asia-southeast1
  MAX_HINT_LEVEL: 3
  ENABLE_LLM: true
  CAS_ENABLED: true
  REGEX_ENABLED: false

handlers:
  - url: /.*
    script: auto
    secure: always
    login: optional

automatic_scaling:
  min_idle_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
